Feature: My feature Contains Corrcet feature description
  Blabla Finastra...

  Scenario: Scenario 1 Correct feature description
    Given Blabla given...
    When Blabla when...
    Then Blabla then...