Feature: My feature Does Not Contain Correct feature description
  Blabla Fin...

  Scenario: Scenario 1 InCorrect feature description
    Given Blabla given...
    When Blabla when...
    Then Blabla then...